// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $central_layout from "./routes/central/_layout.tsx";
import * as $central_index from "./routes/central/index.tsx";
import * as $central_livros_id_index from "./routes/central/livros/[id]/index.tsx";
import * as $central_livros_index from "./routes/central/livros/index.tsx";
import * as $central_registros_id_index from "./routes/central/registros/[id]/index.tsx";
import * as $central_registros_index from "./routes/central/registros/index.tsx";
import * as $central_usuarios_id_index from "./routes/central/usuarios/[id]/index.tsx";
import * as $central_usuarios_index from "./routes/central/usuarios/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $livros_id_ from "./routes/livros/[id].tsx";
import * as $livros_index from "./routes/livros/index.tsx";
import * as $DetailsDropdown from "./islands/DetailsDropdown.tsx";
import * as $Modal from "./islands/Modal.tsx";
import * as $Pagination from "./islands/Pagination.tsx";
import * as $Search from "./islands/Search.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/central/_layout.tsx": $central_layout,
    "./routes/central/index.tsx": $central_index,
    "./routes/central/livros/[id]/index.tsx": $central_livros_id_index,
    "./routes/central/livros/index.tsx": $central_livros_index,
    "./routes/central/registros/[id]/index.tsx": $central_registros_id_index,
    "./routes/central/registros/index.tsx": $central_registros_index,
    "./routes/central/usuarios/[id]/index.tsx": $central_usuarios_id_index,
    "./routes/central/usuarios/index.tsx": $central_usuarios_index,
    "./routes/index.tsx": $index,
    "./routes/livros/[id].tsx": $livros_id_,
    "./routes/livros/index.tsx": $livros_index,
  },
  islands: {
    "./islands/DetailsDropdown.tsx": $DetailsDropdown,
    "./islands/Modal.tsx": $Modal,
    "./islands/Pagination.tsx": $Pagination,
    "./islands/Search.tsx": $Search,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
