// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $central_layout from "./routes/central/_layout.tsx";
import * as $central_index from "./routes/central/index.tsx";
import * as $central_livros_index from "./routes/central/livros/index.tsx";
import * as $central_registros_index from "./routes/central/registros/index.tsx";
import * as $central_usuarios_index from "./routes/central/usuarios/index.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $livros_id_ from "./routes/livros/[id].tsx";
import * as $livros_index from "./routes/livros/index.tsx";
import * as $BookCard from "./islands/BookCard.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Search from "./islands/Search.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/central/_layout.tsx": $central_layout,
    "./routes/central/index.tsx": $central_index,
    "./routes/central/livros/index.tsx": $central_livros_index,
    "./routes/central/registros/index.tsx": $central_registros_index,
    "./routes/central/usuarios/index.tsx": $central_usuarios_index,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/livros/[id].tsx": $livros_id_,
    "./routes/livros/index.tsx": $livros_index,
  },
  islands: {
    "./islands/BookCard.tsx": $BookCard,
    "./islands/Counter.tsx": $Counter,
    "./islands/Search.tsx": $Search,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
